pattern: 'https://github.com/colony-2/${{ cell }}.git'

self:
   repo: https://github.com/colony-2/recipes.git
   ref: main

dependents:
  - https://github.com/colony-2/c2ops.git
  - https://github.com/colony-2/c2j.git


#root:
#  repo: recipes
#  ref: main
